#!/bin/bash

if [ -z $3 ]; then
	echo "Usage: fedbootstrap [suite] [version] [directory] [arch (optional)]"
	exit
fi

suite=$1
version=$2
directory=$3

if [ -z $4 ]; then
	arch=$(uname -m)
else
	arch=$4
fi

# directory must be an absolute path
if [[ $directory != /* ]]; then
	directory=$(pwd)/$directory
fi

TMP_DNF=/tmp/fedbootstrap-dnf.conf
DATA_DIR=/etc/fedbootstrap

if [ "$suite" == "centos" ]; then

	case $version in
		8)
			release=8
			conffile=centos.conf
			;;
		7)
			release=7
			conffile=centos-old.conf
			;;
		6)
			release=6
			conffile=centos-old.conf
			;;
		5)
			release=5
			fullrelease=5.11
			conffile=centos-vault.conf
			;;
		4)
			release=4
			fullrelease=4.9
			conffile=centos-vault.conf
			;;
		*)
			echo "Only CentOS releases 4-8 supported"
			exit
			;;
	esac

	if [ "$version" -ge 8 ]; then
		packagemanager=dnf
	else
		packagemanager=yum
	fi

	# Full release version needs to be specified on CentOS Vault
	if [ "$conffile" == "centos-vault.conf" ]; then
		sed -e 's/$fullreleasever/'"$fullrelease"'/g' $DATA_DIR/centos-vault.conf > $TMP_DNF
	else
		cp $DATA_DIR/$conffile $TMP_DNF
	fi

elif [ "$suite" == "fedora" ]; then

	if [ "$version" -eq 1 ]; then
		echo "Fedora Core 1 is not supported"
		exit
	fi

	if [ "$version" -ge 29 ]; then
		conffile=fedora.conf
	elif [ "$version" -ge 28 ]; then
		conffile=fedora-vault.conf
	elif [ "$version" -ge 7 ]; then
		conffile=fedora-vault-old.conf
	else
		conffile=fedora-core.conf
	fi

	if [ "$version" -ge 22 ]; then
		packagemanager=dnf
	else
		packagemanager=yum
	fi

	cp $DATA_DIR/$conffile $TMP_DNF

else
	echo "Only fedora and centos are supported"
	exit
fi

dnf -y -c $TMP_DNF --skip-broken --installroot="$directory" --releasever="$version" --forcearch=$arch install @Core $packagemanager && \
rm $TMP_DNF && \
rm -rf $directory/var/lib/rpm
