#!/bin/bash

if [ $(command -v dnf) ]; then
	PM=dnf
elif [ $(command -v yum) ]; then
	PM=yum
else
	echo "No package manager found!"
	exit
fi

if [ -z $3 ]; then
	if [ "$PM" == "dnf" ]; then
		echo "Usage: fedbootstrap [suite] [release] [directory] [arch (optional)]"
		exit
	else
		echo "Usage: fedbootstrap [suite] [release] [directory]"
		exit
	fi
fi

suite=$1
release=$2
directory=$3

if [ -z $4 ]; then
	arch=$(uname -m)
else
	arch=$4
fi

# directory must be an absolute path
if [[ $directory != /* ]]; then
	directory=$(pwd)/$directory
fi

TMP_DNF=/tmp/fedbootstrap-dnf.conf
DATA_DIR=/etc/fedbootstrap

if [ "$suite" == "centos" ]; then

	case $release in
		8)
			conffile=centos.conf
			;;
		7)
			conffile=centos-old.conf
			;;
		6)
			conffile=centos-old.conf
			;;
		5)
			fullrelease=5.11
			conffile=centos-vault.conf
			;;
		4)
			fullrelease=4.9
			conffile=centos-vault.conf
			;;
		3)
			fullrelease=3.9
			conffile=centos-vault.conf
			;;
		2)
			echo "CentOS 2 is not supported"
			exit
			;;
		*)
			echo "Only CentOS releases 3-8 supported"
			exit
			;;
	esac

	if [ "$release" -ge 8 ]; then
		packagemanager=dnf
	else
		packagemanager=yum
	fi

	# Full release version needs to be specified on CentOS Vault
	if [ "$conffile" == "centos-vault.conf" ]; then
		sed -e 's/$fullreleasever/'"$fullrelease"'/g' $DATA_DIR/centos-vault.conf > $TMP_DNF
	else
		cp $DATA_DIR/$conffile $TMP_DNF
	fi

elif [ "$suite" == "fedora" ]; then

	if [ "$release" -eq 1 ]; then
		echo "Fedora Core 1 is not supported"
		exit
	fi

	if [ "$release" -ge 29 ]; then
		conffile=fedora.conf
	elif [ "$release" -ge 28 ]; then
		conffile=fedora-vault.conf
	elif [ "$release" -ge 7 ]; then
		conffile=fedora-vault-old.conf
	else
		conffile=fedora-core.conf
	fi

	if [ "$release" -ge 22 ]; then
		packagemanager=dnf
	else
		packagemanager=yum
	fi

	cp $DATA_DIR/$conffile $TMP_DNF

else
	echo "Only fedora and centos are supported"
	exit
fi

if [ "$PM" == "dnf" ]; then
	dnf -y -c $TMP_DNF --skip-broken --installroot="$directory" --releasever="$release" --forcearch=$arch install @Core $packagemanager && \
	rm $TMP_DNF && \
	rm -rf $directory/var/lib/rpm
else
	yum -y -c $TMP_DNF --skip-broken --installroot="$directory" --releasever="$release" install @Core $packagemanager && \
	rm $TMP_DNF && \
	rm -rf $directory/var/lib/rpm
fi

if [ "$release" -le 5 ] && [ "$suite" == "centos" ]; then
	echo ""
	echo "NOTICE: This version of CentOS is deprecated, repositories are now hosted on https://archive.kernel.org/centos-vault/"
	echo "        Package management may not work by default."
elif [ "$release" -le 28 ] && [ "$suite" == "fedora" ]; then
	echo ""
	echo "NOTICE: This version of Fedora is deprecated, repositories are now hosted on https://archive.kernel.org/fedora-archive/"
	echo "        Package management may not work by default."
fi

